@echo off
SET PATHINIT=%PATH%
echo.  ******************                        Compilation de la DLL en mode 64 bits                        *******************
REM Mandatory, add to PATH the binary directory of compiler VisualC/C++ 32 bits + Kits Windows. You can adapt this directory at your personal software environment.
SET PATH=C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\bin\%KIT_WIN_NUM%\x64;C:\Program Files\Microsoft Visual Studio\%VS_VERSION%\Community\VC\Tools\MSVC\%VS_NUM%\bin\Hostx64\x64;%PATH%
SET LIB="C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\lib\%KIT_WIN_NUM%\um\x64";"C:\Program Files\Microsoft Visual Studio\%VS_VERSION%\Community\VC\Tools\MSVC\%VS_NUM%\lib\x64";"C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\lib\%KIT_WIN_NUM%\ucrt\x64";"C:\Program Files\Microsoft Visual Studio\%VS_VERSION%\Community\VC\Tools\MSVC\%VS_NUM%\lib\x64\store"
SET LIBPATH="."
REM Options used with Visual C/C++ compiler 32 bits :
REM 	/Wall								-> set all warning during compilation
REM		/c 									-> compile and assemble only, not call of linker
REM 	/Dxxxxxx							-> define variable xxxxxx used by preprocessor of compiler Visual C/C++
REM 	/Fodll_core.obj 					-> output of object file indicated just after this option 
echo.  ***************       Compilation de la DLL avec Visual C/C++ 64 bits + Kits Windows.             *****************
cl /nologo /Wall /c /TP /DNDEBUG SampleDLL.cpp /FoSampleDLL64.obj /I"C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\include\%KIT_WIN_NUM%\shared" /I"C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\include\%KIT_WIN_NUM%\ucrt" /I"C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\include\%KIT_WIN_NUM%\um" /I"C:\Program Files\Microsoft Visual Studio\%VS_VERSION%\Community\VC\Tools\MSVC\%VS_NUM%\include"
REM Options used with linker Visual C/C++ 32 bits :
REM		/LD									-> generate a shared library => on Window, generate a DLL (Dynamic Linked Library)
REM		/MT                     			-> Use static run-time  
echo.  ***************          Edition de liens de la DLL avec Visual C/C++ 64 bits + Kits Windows.         *******************
cl /nologo /LD /MT /FeSampleDLL64.dll SampleDLL64.obj kernel32.lib user32.lib
echo.  ***************              Listage des fonctions exportees de la DLL                                *******************
REM  	dump result with command "dumpbin" to see exported symbols of dll
dumpbin /exports  SampleDLL64.dll
echo.  *************     Generation et lancement du premier programme de test de la DLL en mode implicite.      *******************
cl /nologo /Wall /c /TP /D_WIN32 /DNDEBUG /FoSampleApp_implicit64.obj SampleApp_implicit.cpp /I"C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\include\%KIT_WIN_NUM%\shared" /I"C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\include\%KIT_WIN_NUM%\ucrt" /I"C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\include\%KIT_WIN_NUM%\um" /I"C:\Program Files\Microsoft Visual Studio\%VS_VERSION%\Community\VC\Tools\MSVC\%VS_NUM%\include"
REM 	Options used by linker of cl /nologoANG/LLVM compiler
REM 		/Fexxxxx 						-> Define output file generated by Visual C/C++ compiler, here exe file
cl /nologo  /FeSampleApp_implicit64.exe SampleApp_implicit64.obj SampleDLL64.lib kernel32.lib user32.lib
REM 	Run test program of DLL with implicit load
SampleApp_implicit64.exe
echo.  ************      Generation et lancement du deuxieme programme de test de la DLL en mode explicite.      *****************
cl /nologo /c /TP /Wall /EHsc /DNDEBUG /D_WIN32 /FoSampleApp_explicit64.obj SampleApp_explicit.cpp /I"C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\include\%KIT_WIN_NUM%\shared" /I"C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\include\%KIT_WIN_NUM%\ucrt" /I"C:\Program Files (X86)\Windows Kits\%KIT_WIN_VERSION%\include\%KIT_WIN_NUM%\um" /I"C:\Program Files\Microsoft Visual Studio\%VS_VERSION%\Community\VC\Tools\MSVC\%VS_NUM%\include"
cl /nologo /FeSampleApp_explicit64.exe SampleApp_explicit64.obj kernel32.lib user32.lib
REM 	Run test program of DLL with explicit load
SampleApp_explicit64.exe
SET PATH=%PATHINIT%
SET "LIB="
